//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalManagmentSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        public int PersonelID { get; set; }
        public string PersonelFirstName { get; set; }
        public string PersonelLastName { get; set; }
        public Nullable<byte> PersonelAge { get; set; }
        public string PersonelAddress { get; set; }
        public Nullable<int> PersonelSalary { get; set; }
        public Nullable<int> PersonelRole { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
